apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "outtune-api"
  namespace: "naisdevice"
  labels:
    "team": "naisdevice"
spec:
  image: {{image}}
  command:
    - /outtune-api
    - --local-ca-enabled=true
    - --local-ca-cert=/tmp/ca-pem/secret
    - --local-ca-key=/tmp/ca-key/secret
  filesFrom:
    - secret: ca-key
      mountPath: /tmp/ca-key
    - secret: ca-pem
      mountPath: /tmp/ca-pem
  liveness:
    path: "/isalive"
    port: 8080
    initialDelay: 2
    timeout: 2
  readiness:
    path: "/isready"
    port: 8080
    initialDelay: 2
    timeout: 2
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  prometheus:
    enabled: false
    path: "/metrics"
  limits:
    cpu: "200m"
    memory: "256Mi"
  requests:
    cpu: "20m"
    memory: "32Mi"
  ingresses:
    {{#each ingresses as |url|}}
    - {{url}}
    {{/each}}
