on:
  push:
    paths:
      - '**.go'
      - 'go.*'
      - Dockerfile
      - 'nais/**.yaml'
      - .github/workflows/ci.yaml

jobs:
  build:
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
    runs-on: ubuntu-20.04
    steps:
      - name: Generate version
        id: generate-version
        run: echo ::set-output name=version::$(date "+%Y-%m-%d-%H%M%S")-$(git rev-parse --short HEAD)
      - name: Docker build
        run: docker build -t ghcr.io/nais/outtune-api:${{ steps.generate-version.outputs.version }} .
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push ghcr.io/nais/outtune-api:${{ steps.generate-version.outputs.version }}


  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Run tests
        run: make test

  deploy:
    name: Deploy to dev-gcp
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          VAR: image=ghcr.io/nais/outtune-api:${{ needs.build.outputs.version }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VARS: nais/dev.yaml
      - uses: nais/deploy/actions/deploy@v1
        if: github.ref == 'refs/heads/main'
        env:
          VAR: image=ghcr.io/nais/outtune-api:${{ needs.build.outputs.version }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais.yaml
          VARS: nais/prod.yaml

