on:
  push:
    paths:
      - '**.go'
      - 'go.*'
      - Dockerfile
      - 'nais/**.yaml'
      - .github/workflows/ci.yaml

env:
  go_version: '1.17'
jobs:
  build:
    outputs:
      version: ${{ steps.generate-version.outputs.version }}
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Generate version
        id: generate-version
        run: echo "version=$(date "+%Y-%m-%d-%H%M%S")-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Docker build
        run: docker build -t ghcr.io/nais/outtune-api:${{ steps.generate-version.outputs.version }} .
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push ghcr.io/nais/outtune-api:${{ steps.generate-version.outputs.version }}


  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.go_version }}
      - name: Run tests
        run: make test

  deploy:
    name: Deploy to gcp
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          VAR: image=ghcr.io/nais/outtune-api:${{ needs.build.outputs.version }}
          APIKEY: ${{ secrets.NAISDEVICE_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: nais/nais.yaml
          VARS: nais/dev.yaml
      - uses: nais/deploy/actions/deploy@v1
        if: github.ref == 'refs/heads/main'
        env:
          VAR: image=ghcr.io/nais/outtune-api:${{ needs.build.outputs.version }}
          APIKEY: ${{ secrets.NAISDEVICE_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: nais/nais.yaml
          VARS: nais/prod.yaml
