on:
  push:
    paths:
      - '**.go'
      - 'go.*'
      - Dockerfile
      - nais.yaml
      - 'nais.d/**.yaml'
      - .github/workflows/ci.yaml

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Compile
        run: make all


  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Run tests
        run: go test ./...
