on:
  push:
    paths:
      - '**.go'
      - 'go.*'
      - Dockerfile
      - nais.yaml
      - 'nais.d/**.yaml'
      - .github/workflows/ci.yaml

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Generate version
        run: echo ::set-output name=version::$(date "+%Y-%m-%d-%H%M%S")-$(git rev-parse --short HEAD)
      - name: Docker build
        run: docker build -t ghcr.io/nais/outtune-api:${{ github_env.version }} .
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@ab80d026d4753220c4243394c07c7d80f9638d06 # Use commit-sha1 instead of tag for security concerns
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push ghcr.io/nais/outtune-api:${{ github_env.version }}


  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Run tests
        run: make test

  deploy_to_dev:
    name: Deploy to dev-gcp
    needs: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/dev.yaml

  deploy_to_prod:
    name: Deploy to prod-gcp
    needs: [ build, deploy_to_dev ]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: .nais/nais.yaml
          VARS: .nais/prod.yaml


